site_name: ClusterPI
site_url: https://kayoo123.github.io/cluster-pi/
site_description: 'Cluster PI'
site_author: Jérémi D.

theme:
  name: material
#  custom_dir: material
#  name: null
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: dark mode
  language: fr
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
    
nav:
    - Accueil: index.md
    - A Propos: about.md
    - Github: https://github.com/kayoo123/cluster-pi
    - 'Issue Tracker': 'https://github.com/kayoo123/cluster-pi/issues'
