site_name: ClusterPI
site_url: https://kayoo123.github.io/cluster-pi/
site_author: Jérémi D.
site_description: >-
  Documentation pour l'installation, la configuration et l'utilisation
  d'un cluster de raspberry-pi. Ceci a pour but educatif sur un ensemble d'outils
  OPS, tel que : Ansible - K3x - helm - traefik - etc...
repo_url: https://github.com/kayoo123/cluster-pi

copyright: Copyright &copy; 2023 - Jérémi D.

theme:
  language: fr
  name: material
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
    repo: fontawesome/brands/github
#  favicon: assets/favicon.png
  features:
    - navigation.footer

#plugins:
#  - minify:
#      minify_html: true
extra:
  generator: false

nav:
    - Préface: index.md
    - Configuration:
      - Hardware: config/hardware.md
      - Software: config/software.md
    - Cluster K3s:
      - Installation: install/k3s
    - A Propos: about.md
